<?php

return [
    '1' => 'user view',
    '2' => 'user create',
    '3' => 'user edit',
    '4' => 'user delete',
    '5' => 'user multiple delete',
    '6' => 'admin view',
    '7' => 'admin create',
    '8' => 'admin edit',
    '9' => 'admin delete',
    '10' => 'admin multiple delete',
    '11' => 'role view',
    '12' => 'role create',
    '13' => 'role edit',
    '14' => 'role delete',
    '15' => 'role multiple delete',
    '16' => 'permission view',
    '17' => 'permission create',
    '18' => 'permission edit',
    '19' => 'permission delete',
    '20' => 'permission multiple delete',
    '21' => 'user active inactive',
    '22' => 'user multiple active',
    '23' => 'user multiple inactive',
    '24' => 'admin active inactive',
    '25' => 'admin multiple active',
    '26' => 'admin multiple inactive',
    '27' => 'page view',
    '28' => 'page create',
    '29' => 'page edit',
    '30' => 'page delete',
    '31' => 'page multiple delete',
    '32' => 'contact us create',
    '33' => 'contact us edit',
    '34' => 'contact us view',
    '35' => 'contact us delete',
    '36' => 'contact us multiple delete',
    '37' => 'web setting view',
    '38' => 'web setting create',
    '39' => 'web setting update',
    '40' => 'push notification create',
    '41' => 'push notification edit',
    '42' => 'push notification view',

];